# Generated by Django 3.2.18 on 2023-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0006_staticpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
    ]
