# Generated by Django 3.2.18 on 2023-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0007_auto_20230424_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_generation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
