# Generated by Django 3.2.18 on 2023-04-27 13:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0008_auto_20230424_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Cre8AI.art User', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqrrhj2ml/image/upload/v1682601722/defaultUser_eqbmfo.png', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
