# Generated by Django 3.2.18 on 2023-04-27 13:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0009_auto_20230427_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dqrrhj2ml/29029f3b5025b2d80d4efa42e027b664', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
