# Generated by Django 3.2.18 on 2023-04-27 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='v1682601722/defaultUser_eqbmfo.png', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
